---
name: Update dependencies

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled

jobs:
  update:
    name: Update dependencies
    timeout-minutes: 45
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ci/update-deps')
    steps:
      - name: Generate Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}

      - name: Remove PR label
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
          REPOSITORY: "${{ github.repository }}"
          PR_NUMBER: "${{ github.event.pull_request.number }}"
        run: |-
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$REPOSITORY/issues/$PR_NUMBER/labels/ci%2Fupdate-deps

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Update dependencies
        run: |
          .github/workflows/scripts/update-node-modules.sh update

      - name: Commit updated dependencies
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Update checked-in dependencies"
          file_pattern: "node_modules/*"
          commit_user_name: "${{ vars.LAB_ASSISTANT_USERNAME }}"
          commit_user_email: "${{ vars.LAB_ASSISTANT_EMAIL }}"
          commit_author: "${{ vars.LAB_ASSISTANT_USERNAME }} <${{ vars.LAB_ASSISTANT_EMAIL }}>"
